# ------------------------------------------------------------------------------
# PulsePipe — Ingest, Normalize, De-ID, Embed. Healthcare Data, AI-Ready.
# https://github.com/PulsePipe/pulsepipe
#
# Copyright (C) 2025 Amir Abrams
#
# This file is part of PulsePipe and is licensed under the GNU Affero General 
# Public License v3.0 (AGPL-3.0). A full copy of this license can be found in 
# the LICENSE file at the root of this repository or online at:
# https://www.gnu.org/licenses/agpl-3.0.html
#
# PulsePipe is distributed WITHOUT ANY WARRANTY; without even the implied 
# warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# We welcome community contributions — if you make it better, 
# share it back. The whole healthcare ecosystem wins.
# ------------------------------------------------------------------------------
# 
# PulsePipe - Open Source ❤️, Healthcare Tough 💪, Builders Only 🛠️
# ------------------------------------------------------------------------------

deid:
  # HIPAA Safe Harbor method with healthcare NER enhancements
  method: safe_harbor
  keep_year: true
  geographic_precision: state
  over_90_handling: redact
  patient_id_strategy: hash
  id_salt: changeme1234
  
  # Healthcare NER with Microsoft Presidio
  use_presidio_for_text: true
  log_detected_entities: false  # Set to true for debugging
  
  # Healthcare-specific entity detection
  presidio_entities:
    # Standard PHI entities
    - "PERSON"
    - "EMAIL_ADDRESS" 
    - "PHONE_NUMBER"
    - "US_SSN"
    - "CREDIT_CARD"
    - "US_DRIVER_LICENSE"
    - "DATE_TIME"
    
    # Healthcare-specific entities (enhanced with biomedical NER)
    - "MEDICAL_RECORD_NUMBER"
    - "MEDICAL_LICENSE"
    - "UK_NHS"
    - "MEDICATION"
    - "MEDICAL_CONDITION"
    - "MEDICAL_PROCEDURE"
    - "BODY_PART"
    - "MEDICAL_DEVICE"
    - "LAB_VALUE"
  
  # Legacy configuration (regex-only, no healthcare NER)
  # use_presidio_for_text: false