name: Run Pytest

on:
  push:
    branches: [main]
  pull_request:
    branches: ['*']

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install

      - name: Run pytest (skip vectorstore tests in CI)
        run: |
          poetry run pytest \
            --ignore=tests/test_vectorstore_qdrant_store.py \
            --ignore=tests/test_vectorstore_weaviate_store.py \
            --ignore=tests/test_vectorstore_stage.py
